import Head from 'next/head'
import Footer from '../src/components/Footer/Footer'
import Header from '../src/components/Header/Header'
import styles from '../styles/Home.module.scss'
import Image from 'next/image'
import SingleCardStandard from "../src/components/common/SingleCard/SingleCardStandard";
import {singleCardStandardData} from "../data/singleCardStandardData";
import singleCardStandard from "../src/components/common/SingleCard/SingleCardStandard";


export default function Home() {
    return (
        <>
            <Head>
                <title>Netflix Clone App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.singleCard}>
                    <div className={styles.cardBackground}>
                        <div className={styles.imageWrapper}>
                            <Image
                                src="/misc/home-bg.jpg"
                                alt="Netflix logo"
                                layout="fill"
                                objectFit="cover"
                                className={styles.bgImage}
                            />
                            <div className={styles.imageGradient}>
                                image gradient
                            </div>
                        </div>
                    </div>
                    <div className={styles.cardText}>
                        mainTexts
                    </div>
                </div>
                <SingleCardStandard
                    headerOne = {singleCardStandardData[0].headerOne}
                    headerSubtitle={singleCardStandardData[0].headerSubtitle}
                    imgSrc={singleCardStandardData[0].imgSrc}
                    imgAlt={singleCardStandardData[0].imgAlt}
                    videoSrc={singleCardStandardData[0].videoSrc}
                    videoClass={singleCardStandardData[0].videoClass}
                />
                <SingleCardStandard
                    headerOne = {singleCardStandardData[1].headerOne}
                    headerSubtitle={singleCardStandardData[1].headerSubtitle}
                    imgSrc={singleCardStandardData[1].imgSrc}
                    imgAlt={singleCardStandardData[1].imgAlt}
                    videoSrc={singleCardStandardData[1].videoSrc}
                    videoClass={singleCardStandardData[1].videoClass}
                />
                <SingleCardStandard
                    headerOne = {singleCardStandardData[2].headerOne}
                    headerSubtitle={singleCardStandardData[2].headerSubtitle}
                    imgSrc={singleCardStandardData[2].imgSrc}
                    imgAlt={singleCardStandardData[2].imgAlt}
                    videoSrc={singleCardStandardData[2].videoSrc}
                    videoClass={singleCardStandardData[2].videoClass}
                />
                <SingleCardStandard
                    headerOne = {singleCardStandardData[3].headerOne}
                    headerSubtitle={singleCardStandardData[3].headerSubtitle}
                    imgSrc={singleCardStandardData[3].imgSrc}
                    imgAlt={singleCardStandardData[3].imgAlt}
                    videoSrc={singleCardStandardData[3].videoSrc}
                    videoClass={singleCardStandardData[3].videoClass}
                />
            </main>
        </>
    )
}
