import Head from 'next/head'
import Footer from '../src/components/Footer/Footer'
import Header from '../src/components/Header/Header'
import styles from '../styles/Home.module.scss'
import Image from 'next/image'


export default function Home() {
    return (
        <>
            <Head>
                <title>Netflix Clone App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.singleCard}>
                    <div className={styles.cardBackground}>
                        <div className={styles.imageWrapper}>
                            <Image
                                src="/misc/home-bg.jpg"
                                alt="Netflix logo"
                                layout="fill"
                                objectFit="cover"
                                className={styles.bgImage}
                            />
                            <div className={styles.imageGradient}>
                                image gradient
                            </div>
                        </div>
                    </div>
                    <div className={styles.cardText}>
                        mainTexts
                    </div>
                </div>
                <div className={styles.singleCardStandard}>
                    <div className={styles.singleCardStandardContainer}>
                        <div className={styles.singleCardStandardText}>
                            <h1 className={styles.singleCardStandardTitle}>
                                Enjoy on your TV.
                            </h1>
                            <h2 className={styles.singleCardStandardSubtitle}>
                                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
                            </h2>
                        </div>
                        <div className={styles.singleCardStandardImgContainer}>
                            <div className={styles.singleCardStandardImg}>
                                <img
                                    className={styles.standardImage}
                                    src="/misc/tv.png"
                                    alt="TV Icon"
                                />
                                <div className={styles.singleCardStandardVideoContainer}>
                                    <video className={styles.singleCardVideo} autoPlay={true} playsInline={true} muted={true} loop={true}>
                                        <source src="/misc/video-tv-0819.m4v" type="video/mp4"/>
                                    </video>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </main>

        </>
    )
}
