import Head from 'next/head'
import Footer from './components/Footer/Footer'
import Header from './components/Header/Header'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix Clone App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <Header/>
        <h1>Hello</h1>
          <Footer/>
      </main>

    </>
  )
}
